flowchart TD

clk --> FPGA
rst --> FPGA
BTN_SEL[BTN_SEL] -->|sel|M09
BTN_OK[BTN_OK] -->|ok|M09

subgraph "UART"[UART \n TX/RX 115200 baud]
    REG_DATA["REG_DATA"]
    REG_CTRL["REG_CTRL"]
    
end

subgraph "LCD"
    REG_LCD["REG_LCD"]
    REG_CTRL_LCD["REG_CTRL_LCD"]
    
end

UART -->|"letra(32)"| M10
PC -->|"letra(32)"| UART



LETRA-..->PC
subgraph "PC"
    App["App"]

end

subgraph "FPGA"
    FSM["FSM"]
    FSM-->|state|M05
    FSM-->|start|M03
    FSM-->|choose|M08

    FSM-->|load|REG_WI

    FSM-->|start|M02
    FSM-->|show|M04
    FSM-->|count|M06
    

    M01["M01_Marcador"]
    M02["M02_Buzzer"]
    M03["M03_Timer"]
    M04["M04_showLCD"]
    M05["M05_State"]
    M06["M06_Ganadas"]
    M07["M07_Comparador-letra"]
    M08["M08_LFSR"]
    M09["M09_Press-Btn"]
    M10["M10_R-UART"]
    M11["M11_T-UART"]
    M12["M12_Try-Counter"]

    M09-->|sel|FSM
    M09-->|ok|FSM
    FSM-->|modo|M04
    FSM-->|modo|M08
    FSM-->|modo|M03
    FSM-->|modo|M11
    M07-->|try|M12
    M07-->|letra_state|M02

    

    M10-->|word_in|REG_WI

    REG_WS[REG_WBank] -->|bank_word| M08
    M08 --> |word|REG_W


    M03-->|time|M01
    M06-->|num_ganadas|M01
    REG_WI -->|word_in|M07

    REG_W[REG_Palabra-escogida] 
    REG_WI-->|word|M04
    REG_W-->|word|M07
    M08-->|valid_word|FSM
    REG_WI[REG_Palabra-in]

    M07-->|letra_state|FSM
    M07-->|letra_state|M11

    M10-->|valid_w|FSM
    M12-->|try|FSM
    REG_W-->|word_length|M11
    
end

M01-->|time|7SEG1["7SEG TIEMPO"]
M01-->|num_win|7SEG2["7SEG GANADAS"]
M02-->|sound|BUZZER["BUZZER"]
M05-->|state|LED_S["LED ESTADO"]
M04-->|word/Modo|LCD
M11-->|modo/letra_state/Resultado/w_word/Intentos|UART
M12-->|try|M11