flowchart TD

clk --> FPGA
BTN_RST[BTN_RST] --> FPGA
BTN_SEL[BTN_SEL] -->|sel|M09
BTN_OK[BTN_OK] -->|ok|M09

PC -->|"RX serial"| PERIFERICO_UART



LETRA-..->PC
subgraph "PC"
    App["App"]

end

subgraph "PERIFERICO_UART"[PERIFERICO_UART \n TX/RX 115200 baud]
        REG_CTRL["REG_CTRL\nsend(0,WC) new_rx(1,RW)"]
        REG_DATOS_TX["REG_DATOS_TX"]
        REG_DATOS_RX["REG_DATOS_RX"]

    end

subgraph "PERIFERICO_LCD"
        REG_CTRL_LCD["REG_CTRL_ESTADO\nstart(0,W1P) rs(1) clear(2,W1P) home(3,W1P) busy(8,RO) done(9,RO)"]
        REG_LCD["REG_DATOS\ndata_byte(7:0)"]

    end
subgraph "FPGA"

    
    

    subgraph "CONTROL_JUEGO"
        FSM["FSM"]
        M04["M04_Mostrar-LCD"]
        M07["M07_Comparador-letra"]
        M10["M10_Receptor-UART"]
        M11["M11_Transmisor-UART"]
        M12["M12_Contador-Intentos"]
        REG_W[REG_Palabra-escogida]
        REG_LI[REG_Letra-in]

        FSM-->|load|REG_LI
        FSM-->|show|M04
        FSM-->|modo|M04
        FSM-->|modo|M11
        M07-->|try|M12
        M10-->|letra_in|REG_LI
        REG_LI-->|letra_in|M07
        REG_LI-->|letra_in|M04
        REG_W-->|word|M07
        M07-->|letra_state|FSM
        M07-->|letra_state|M11
        M10-->|valid_w|FSM
        M12-->|try|FSM
        M12-->|try|M11
        REG_W-->|word_length|M11
    end

    subgraph "BANCO_PALABRAS"
        M08["M08_LFSR"]
        REG_WS[REG_WBank]

        REG_WS-->|bank_word|M08
    end

    subgraph "TEMPORIZADOR"
        M03["M03_Temporizador"]
    end

    subgraph "E_S_LOCALES"
        M01["M01_Marcador"]
        M02["M02_Generador-Tono"]
        M05["M05_Estado"]
        M06["M06_Ganadas"]
        M09["M09_Antirrebote"]

        M06-->|num_ganadas|M01
    end

    

    FSM-->|state|M05
    FSM-->|start|M03
    FSM-->|detener|M03
    FSM-->|choose|M08
    FSM-->|start|M02
    FSM-->|count|M06
    FSM-->|modo|M08
    FSM-->|modo|M03
    M07-->|letra_state|M02
    M08-->|word|REG_W
    M08-->|valid_word|FSM
    M03-->|tiempo_agotado|FSM
    M03-->|time|M01
    M09-->|sel|FSM
    M09-->|ok|FSM

end

M01-->|time|7SEG1["7SEG TIEMPO"]
M01-->|num_win|7SEG2["7SEG GANADAS"]
M02-->|sound|BUZZER["BUZZER"]
M05-->|state|LED_S["LED ESTADO"]
M04-->|word/Modo|PERIFERICO_LCD
M11-->|modo/letra_state/Resultado/w_word/Intentos|PERIFERICO_UART

CONTROL_JUEGO <-->|"bus 32b"| PERIFERICO_UART
CONTROL_JUEGO <-->|"bus 32b"| PERIFERICO_LCD